spring:
  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      ddl-auto: update
      globally_quoted_identifiers: true
      format_sql: true
      use_sql_comments: true


datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:tcp://localhost:9092/~/test
  username: sa
  password: